# Generated by Django 4.0.5 on 2023-07-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculomodel',
            name='categoria',
            field=models.CharField(default='Particular', max_length=20),
        ),
    ]
